on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: r-hub

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    container:
      image: rhub/${{ matrix.config.image }}

    name: rhub/${{ matrix.config.image }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: ubuntu-16.04,
              image: "ubuntu-gcc-release",
              cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest",
            }
          - {
              os: ubuntu-16.04,
              image: "debian-gcc-release",
              cran: "https://cran.rstudio.com/",
            }

    env:
      CRAN: ${{ matrix.config.cran }}

    steps:
      - uses: actions/checkout@v2

      - name: Query dependencies
        run: |
          options(warn = 2)
          install.packages('remotes', repos = Sys.getenv("CRAN"))
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ runner.os }}-image-rhub-${{ matrix.config.image }}-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-image-rhub-${{ matrix.config.image }}-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          Rscript -e "options(warn = 2); remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          eval "$sysreqs"

      - name: Install dependencies
        run: |
          options(warn = 2)
          remotes::install_deps(dependencies = TRUE, repos = Sys.getenv("CRAN"))
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-image-rhub-${{ matrix.config.image }}-results
          path: check
